ALIYUN_ECS_SPEC_DEFINITIONS = {
    "compute.vcpu_count": ("vCPU count", "numeric", "count"),
    "compute.memory_gib": ("Memory", "numeric", "GiB"),
    "compute.cpu_architecture": ("CPU architecture", "text", None),
    "compute.processor_vendor": ("Processor vendor", "text", None),
    "compute.processor_model": ("Processor model", "text", None),
    "network.baseline_bandwidth_gbps": ("Baseline network bandwidth", "numeric", "Gbps"),
    "network.max_bandwidth_gbps": ("Maximum network bandwidth", "numeric", "Gbps"),
    "network.max_pps": ("Maximum packets per second", "numeric", "PPS"),
    "network.max_connections": ("Maximum network connections", "numeric", "count"),
    "network.cloud_disk_bandwidth_gbps": ("Cloud disk bandwidth", "numeric", "Gbps"),
    "storage.cloud_disk_iops": ("Cloud disk IOPS", "numeric", "IOPS"),
    "storage.local_disk_count": ("Local disk count", "numeric", "count"),
    "storage.local_disk_capacity_gib": ("Local disk capacity", "numeric", "GiB"),
    "storage.local_disk_type": ("Local disk type", "text", None),
    "gpu.count": ("GPU count", "numeric", "count"),
    "gpu.model": ("GPU model", "text", None),
    "system.instance_family_level": ("Instance family level", "text", None),
}
